### ISSUE TITLE
Fix the Infinity Winning Bug

### ISSUE THREAD

**Issue by Balaguru4580** [Balaguru4580/Angular-TicTacToe#3]
Once any player wins, pressing on any buttons that aren't disabled within the board results in an increment in the winner's score. This happens on every click! This can obviously be manipulated to get CRAZY scores! 😆 

I assume it would require an additional condition somewhere. So, I hope someone can figure it out.

**Comment by xshadowlegendx** [comment]
I am claiming this issue

**Comment by Balaguru4580** [comment]
Sure. I'll assign you to it.

**Comment by Balaguru4580** [comment]
Verified. It's working. Thanks man!
