### ISSUE TITLE
Single-Player Toggle needs to be disabled during game.

### ISSUE THREAD

**Issue by Balaguru4580** [Balaguru4580/Angular-TicTacToe#5]
The single-player mode toggle is currently toggleable even while a round of tic-tac-toe round is in progress. It should only be toggleable before or after any given tic-tac-toe round.

Ideally, the toggle should be disabled during a tic-tac-toe round and should be re-enabled when the round is over.

**Comment by JasonFritsche** [comment]
I'd like to work on this issue.
