### ISSUE TITLE
Delay Opponent Moves in Single-Player Mode

### ISSUE THREAD

**Issue by Balaguru4580** [Balaguru4580/Angular-TicTacToe#8]
In the Single-Player mode, a CPU or Opponent move is made instantly upon a move by the user. While this isn't game-breaking, it's still very unnatural in terms of feel.

[Here's a GIF reproducing this.](http://g.recordit.co/w3rPjAClMz.gif)

A tiny delay before the Opponent move would be nice to maintain the pace of the game. It's a simple fix, but helps make the game feel smooth.

**Comment by W01fw00d** [comment]
Hi! Can I work on this issue if that's ok with you? I can produce a PR to implement this.

How much time would you like for the delay? Half a second, 1 second...?

**Comment by Balaguru4580** [comment]
@W01fw00d Sure! I'm thinking of half a second, but go ahead and experiment with that delay length. Just ensure that it's not distracting.
